apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "rmt.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rmt.name" . }}
    helm.sh/chart: {{ include "rmt.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rmt.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "rmt.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "rmt.fullname" . }}
      containers:
        - name: rmt-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: /usr/share/rmt
          lifecycle:
            postStart:
              exec:
                command: ['/usr/share/rmt/bin/rails', 'db:create', 'db:migrate', 'RAILS_ENV=production']
          ports:
            - name: http
              containerPort: 4224
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health/status
              port: http
          readinessProbe:
            httpGet:
              path: /api/health/status
              port: http
          volumeMounts:
            - name: config-volume
              mountPath: /etc/rmt.conf
              subPath: rmt.conf
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
